export const SKILL_SLUG_TO_DISPLAY: Record<string, string> = {
  "carpenter": "Carpenter",
  "electrician": "Electrician",
  "fitter": "Fitter",
  "foreman": "Foreman",
  "glass-aluminium-fitter": "Glass/Aluminium Fitter",
  "interior-skimmer": "Interior Skimmer",
  "mason": "Mason",
  "painter": "Painter",
  "plumber": "Plumber",
  "roofer": "Roofer",
  "steel-fixer": "Steel Fixer",
  "tile-fixer": "Tile Fixer",
  "welder": "Welder",
};

// Resolve a skill slug or display name to a friendly display name
export const resolveSkillName = (raw: string): string => {
  const trimmed = raw.trim();
  if (!trimmed) return "";
  if (SKILL_SLUG_TO_DISPLAY[trimmed]) return SKILL_SLUG_TO_DISPLAY[trimmed];
  // Check case-insensitive match against display names
  const lowerTrimmed = trimmed.toLowerCase();
  if (SKILL_SLUG_TO_DISPLAY[lowerTrimmed]) return SKILL_SLUG_TO_DISPLAY[lowerTrimmed];
  // Already a display name or unknown — title-case as fallback
  if (trimmed.includes("-")) {
    return trimmed.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
  }
  return trimmed.charAt(0).toUpperCase() + trimmed.slice(1);
};

// Build a full URL for server-relative paths (e.g. /media/uploads/...)
export const FUNDI_SPECIALIZATIONS = {
  Carpenter: [
    "Furniture Making",
    "Roof Carpentry",
    "Formwork & Shuttering",
    "Door & Window Fitting",
    "Cabinet Making",
    "Ceiling & Partition",
    "General Carpentry",
  ],
  Electrician: [
    "Domestic Wiring",
    "Commercial Wiring",
    "Industrial Wiring",
    "Solar Installation",
    "Fire Alarm Systems",
    "CCTV & Security Systems",
    "General Electrical",
  ],
  Fitter: [
    "Mechanical Fitting",
    "Pipe Fitting",
    "Structural Fitting",
    "Machine Installation",
    "Maintenance Fitting",
    "General Fitting",
  ],
  Foreman: [
    "Site Supervision",
    "Project Coordination",
    "Quality Control",
    "Safety Management",
    "General Supervision",
  ],
  "Glass/Aluminium Fitter": [
    "Window Installation",
    "Door Installation",
    "Curtain Walling",
    "Shower Enclosures",
    "Mirror Fitting",
    "Shopfront Glazing",
    "General Glass & Aluminium",
  ],
  "Interior Skimmer": [
    "Wall Skimming",
    "Ceiling Skimming",
    "Decorative Plaster",
    "Cornices & Mouldings",
    "General Skimming",
  ],
  Mason: [
    "Block Work",
    "Stone Masonry",
    "Brick Laying",
    "Plastering",
    "Foundation Work",
    "Concrete Work",
    "General Masonry",
  ],
  Painter: [
    "Interior Painting",
    "Exterior Painting",
    "Spray Painting",
    "Decorative Painting",
    "Waterproofing & Coating",
    "Wallpapering",
    "General Painting",
  ],
  Plumber: [
    "General Plumbing",
    "Water Systems",
    "Drainage & Sewer",
    "Gas Plumbing",
    "Bathroom Installation",
    "Kitchen Installation",
    "Pipe Welding",
    "Solar Water Systems",
  ],
  Roofer: [
    "Iron Sheet Roofing",
    "Tile Roofing",
    "Flat Roof & Waterproofing",
    "Roof Repair & Maintenance",
    "Gutter Installation",
    "General Roofing",
  ],
  "Steel Fixer": [
    "Slab Reinforcement",
    "Column & Beam Fixing",
    "Foundation Steel Fixing",
    "Retaining Wall Reinforcement",
    "Bar Bending & Cutting",
    "General Steel Fixing",
  ],
  "Tile Fixer": [
    "Floor Tiling",
    "Wall Tiling",
    "Bathroom & Kitchen Tiling",
    "Outdoor & Paving Tiles",
    "Mosaic & Decorative Tiling",
    "General Tiling",
  ],
  Welder: [
    "Arc Welding",
    "MIG Welding",
    "TIG Welding",
    "Gate & Grille Fabrication",
    "Structural Welding",
    "Pipe Welding",
    "General Welding",
  ],
};

export const PROFESSIONAL_SPECIALIZATIONS = {
  "Project Manager": [
    "Construction Project Management",
    "Infrastructure Projects",
    "Residential Development",
    "Commercial Development",
    "Industrial Projects",
    "Government Projects",
    "Real Estate Development",
    "Renovation & Remodeling",
    "Green Building Projects",
    "Multi-site Management",
  ],
  Architect: [
    "Residential Architecture",
    "Commercial Architecture",
    "Industrial Architecture",
    "Landscape Architecture",
    "Interior Architecture",
    "Urban Planning",
    "Sustainable Design",
    "Historic Preservation",
    "Healthcare Facilities",
    "Educational Facilities",
  ],
  "Water Engineer": [
    "Water Supply Systems",
    "Wastewater Treatment",
    "Stormwater Management",
    "Irrigation Engineering",
    "Hydraulic Structures",
    "Pipeline Engineering",
    "Water Resources Management",
    "Flood Control",
    "Desalination Systems",
    "Environmental Water Solutions",
  ],
  "Roads Engineer": [
    "Highway Design",
    "Urban Road Design",
    "Pavement Engineering",
    "Traffic Engineering",
    "Bridge Engineering",
    "Road Rehabilitation",
    "Drainage Design",
    "Survey & Mapping",
    "Construction Supervision",
    "Road Safety Engineering",
  ],
  "Structural Engineer": [
    "Building Structures",
    "Bridge Structures",
    "Industrial Structures",
    "Concrete Structures",
    "Steel Structures",
    "Foundation Engineering",
    "Seismic Design",
    "Structural Assessment",
    "Retrofit & Rehabilitation",
    "Temporary Structures",
  ],
  "Mechanical Engineer": [
    "HVAC Systems",
    "Plumbing Systems",
    "Fire Protection Systems",
    "Elevator & Escalator Systems",
    "Industrial Machinery",
    "Energy Systems",
    "Building Automation",
    "Refrigeration Systems",
    "Ventilation Design",
    "Mechanical Maintenance",
  ],
  "Electrical Engineer": [
    "Power Distribution",
    "Lighting Design",
    "Building Electrical Systems",
    "Industrial Electrical",
    "Renewable Energy Systems",
    "Control Systems",
    "Telecommunications",
    "Security Systems",
    "Fire Alarm Systems",
    "Energy Management",
  ],
  Surveyor: [
    "Land Surveying",
    "Topographic Surveys",
    "Construction Surveying",
    "Cadastral Surveys",
    "Engineering Surveys",
    "GPS & GIS Mapping",
    "Hydrographic Surveys",
    "Quantity Surveying",
    "Boundary Surveys",
    "As-built Surveys",
  ],
  "Quantity Surveyor": [
    "Cost Estimation",
    "Bill of Quantities",
    "Contract Administration",
    "Value Engineering",
    "Project Cost Control",
    "Procurement Management",
    "Final Account Settlement",
    "Risk Assessment",
    "Feasibility Studies",
    "Life Cycle Costing",
  ],
};

export const CONTRACTOR_SPECIALIZATIONS = {
  "Building Works": [
    "Residential Construction",
    "Commercial Construction",
    "Industrial Construction",
    "Institutional Buildings",
    "High-rise Buildings",
    "Housing Estates",
    "Renovation & Remodeling",
    "Prefabricated Construction",
    "Green Building Construction",
    "Mixed-use Developments",
  ],
  "Water Works": [
    "Water Supply Systems",
    "Irrigation Systems",
    "Sewer/Sanitation Systems",
  ],
  "Electrical Works": [
    "Power Line Installation",
    "Substation Construction",
    "Building Electrical Works",
    "Street Lighting",
    "Solar Power Installation",
    "Generator Installation",
    "Industrial Electrical",
    "Fire Alarm Systems",
    "Security Systems Installation",
    "Smart Building Systems",
  ],
  "Mechanical Works": [
    "HVAC Installation",
    "Plumbing & Sanitary Works",
    "Fire Fighting Systems",
    "Elevator & Escalator Installation",
    "Industrial Equipment Installation",
    "Refrigeration Systems",
    "Compressed Air Systems",
    "Steam & Boiler Systems",
    "Piping Works",
    "Mechanical Maintenance",
  ],
  "Roads & Infrastructure": [
    "Road Construction",
    "Bridge Construction",
    "Culvert Construction",
    "Drainage Systems",
    "Pavement Works",
    "Highway Construction",
    "Airport Runways",
    "Railway Construction",
    "Port & Marine Works",
    "Urban Infrastructure",
  ],
  "Landscaping & External Works": [
    "Landscape Construction",
    "Paving & Hardscaping",
    "Fencing & Gates",
    "Swimming Pool Construction",
    "Sports Facilities",
    "Playground Construction",
    "Retaining Walls",
    "Outdoor Lighting",
    "Irrigation Installation",
    "Environmental Landscaping",
  ],
};


export const CATEGORY_OPTIONS = [
  "Building Works",
  "Water Works",
  "Electrical Works",
  "Mechanical Works",
];

export const FUNDI_GRADE_OPTIONS = [
  "G1: Master Fundi",
  "G2: Skilled",
  "G3: Semi-skilled",
  "G4: Unskilled",
];

export const FUNDI_EXPERIENCE_OPTIONS = [
  "10+ years",
  "5-10 years",
  "3-5 years",
  "1-3 years",
];

export const FUNDI_GRADE_PROJECT_COUNT: Record<string, number> = {
  "G1: Master Fundi": 3,
  "G2: Skilled": 2,
  "G3: Semi-skilled": 1,
  "G4: Unskilled": 0,
};
